<?php
// PHP EMS Tools
// Version Information
//
// This file is REQUIRED in order to run PHP EMS Tools

// DO NOT EDIT THIS FILE
$verTimeStamp = 'Time-stamp: "2007-09-13 16:16:10 jantman"';

$verNum = 2.0;
$verStr = "Release 2";

?>